version: 1
formatters:
  brief:
    format: '%(levelname)-7s %(asctime)15s %(name)s %(message)s'
    datefmt: '%y-%m-%d,%H:%M:%S'
  precise:
    format: '%(levelname)-7s %(asctime)15s %(name)s:%(lineno)d %(message)s'
    datefmt: '%y-%m-%d,%H:%M:%S'
# this one should only be used by handlers that support topology_id attribute
# and since it may be used by multiple modules, actual_module attribute
# should also be added (module will give a short name, pathname is too long)

handlers:
  console:
    class : logging.StreamHandler
    formatter: precise
    stream  : ext://sys.stderr

loggers:
# by default all existing loggers are disabled upon the application
# of this config. To re-enable a logger and it's childer just add it
# to the loggers section with any even empty fields.
  pika:
    handlers: [console]
    level: WARNING
    propagate: False

  helix: {}

root:
  handlers: [console]
  level: DEBUG

